ALTER TABLE files
    ADD COLUMN IF NOT EXISTS storage_kind TEXT NOT NULL DEFAULT 'text',
    ADD COLUMN IF NOT EXISTS content_bytes BYTEA,
    ADD COLUMN IF NOT EXISTS content_oid OID,
    ADD COLUMN IF NOT EXISTS byte_size BIGINT,
    ADD COLUMN IF NOT EXISTS content_sha256 TEXT;

ALTER TABLE sync_events
    ADD COLUMN IF NOT EXISTS content_bytes BYTEA,
    ADD COLUMN IF NOT EXISTS storage_kind TEXT,
    ADD COLUMN IF NOT EXISTS byte_size BIGINT,
    ADD COLUMN IF NOT EXISTS content_sha256 TEXT;
