import esbuild from "esbuild";
import process from "process";
import { createRequire } from "node:module";
import { builtinModules } from "node:module";

const require = createRequire(import.meta.url);
const yjsEntry = require.resolve("yjs");

/** One Yjs instance per bundle — shared/ has its own node_modules/yjs otherwise. */
const yjsDedupePlugin = {
	name: "yjs-dedupe",
	setup(build) {
		build.onResolve({ filter: /^yjs$/ }, () => ({ path: yjsEntry }));
	},
};

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	define: {
		__SYNC_LOG_LEVEL__: JSON.stringify(prod ? "warn" : "debug"),
	},
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [yjsDedupePlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
