name: Node.js build

on:
    push:
        branches: [diy-object-store]
    pull_request:
        branches: ['**']

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: plugin

        steps:
            - uses: actions/checkout@v6
            - name: Use Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: 22.x
                  cache: 'npm'
                  cache-dependency-path: |
                      plugin/package-lock.json
                      shared/protocol/package-lock.json
            - name: Install protocol deps
              working-directory: shared/protocol
              run: npm ci
            - run: npm ci
            - run: npm run build --if-present
            - run: npm run lint
